### ISSUE TITLE
Is this PHP extension still supported ?

### ISSUE THREAD

**Issue by melicerte** [weltling/parle#21]
Hi,

the extension seems great, but it looks like it's not under active development.
The PHP 7.4 issue has not been released and last activity from maintainers is summer 2019.

@remicollet do you plan to maintain the extension, including for current and future releases of PHP ?

**Comment by remicollet** [comment]
see PR #22

**Comment by weltling** [comment]
Pulled via 293b88cbd647a79570d654bc4862f0c25b95085a. Thanks!
