### ISSUE TITLE
[feature request] sigil get token or rule name

### ISSUE THREAD

**Issue by lublak** [weltling/parle#25]
currently there is no way to get the name behind a sigil.
It can be helpful to debug your parser.

```php
$infos = $parser->getSigilInfos(0); // => SigilInfos
$infos->getName();
$infos->isToken();
```

**Comment by BenHanson** [comment]
By the time the state machine is created, there are no names any more only numbers. This is why you record the rule index returned from push() so you know which rule you are talking about.

**Comment by BenHanson** [comment]
Added `$parser->sigilName(0);`
